# Stage 1: Build
FROM node:22-alpine AS builder
WORKDIR /app

RUN npm install -g pnpm

COPY package.json pnpm-lock.yaml ./
RUN pnpm install --frozen-lockfile

COPY . .

# Variables PUBLIC_* procesadas por Vite en tiempo de build.
# En Dokploy: defínelas en "Build Arguments" del servicio.
ARG PUBLIC_API_URL
ARG PUBLIC_BRAND_NAME
ARG PUBLIC_BRAND_TAGLINE
ARG PUBLIC_SITE_URL
ARG PUBLIC_LOGO_PATH
ARG PUBLIC_FAVICON_PATH
ARG PUBLIC_COLOR_PRIMARY
ARG PUBLIC_COLOR_SECONDARY
ARG PUBLIC_COLOR_ACCENT
ARG PUBLIC_SERVICE_HOTELS
ARG PUBLIC_SERVICE_TOURS
ARG PUBLIC_SERVICE_TRANSFERS
ARG PUBLIC_WHATSAPP
ARG PUBLIC_PHONE
ARG PUBLIC_EMAIL
ARG PUBLIC_ADDRESS
ARG PUBLIC_SOCIAL_FACEBOOK
ARG PUBLIC_SOCIAL_INSTAGRAM
ARG PUBLIC_LOCATION_NAME
ARG PUBLIC_LOCATION_REGION
ARG PUBLIC_LOCATION_COUNTRY
ARG PUBLIC_LOCATION_DESC
ARG PUBLIC_SEO_KEYWORDS
ARG PUBLIC_GA_ID
ARG PUBLIC_FB_PIXEL

ENV PUBLIC_API_URL=$PUBLIC_API_URL \
    PUBLIC_BRAND_NAME=$PUBLIC_BRAND_NAME \
    PUBLIC_BRAND_TAGLINE=$PUBLIC_BRAND_TAGLINE \
    PUBLIC_SITE_URL=$PUBLIC_SITE_URL \
    PUBLIC_LOGO_PATH=$PUBLIC_LOGO_PATH \
    PUBLIC_FAVICON_PATH=$PUBLIC_FAVICON_PATH \
    PUBLIC_COLOR_PRIMARY=$PUBLIC_COLOR_PRIMARY \
    PUBLIC_COLOR_SECONDARY=$PUBLIC_COLOR_SECONDARY \
    PUBLIC_COLOR_ACCENT=$PUBLIC_COLOR_ACCENT \
    PUBLIC_SERVICE_HOTELS=$PUBLIC_SERVICE_HOTELS \
    PUBLIC_SERVICE_TOURS=$PUBLIC_SERVICE_TOURS \
    PUBLIC_SERVICE_TRANSFERS=$PUBLIC_SERVICE_TRANSFERS \
    PUBLIC_WHATSAPP=$PUBLIC_WHATSAPP \
    PUBLIC_PHONE=$PUBLIC_PHONE \
    PUBLIC_EMAIL=$PUBLIC_EMAIL \
    PUBLIC_ADDRESS=$PUBLIC_ADDRESS \
    PUBLIC_SOCIAL_FACEBOOK=$PUBLIC_SOCIAL_FACEBOOK \
    PUBLIC_SOCIAL_INSTAGRAM=$PUBLIC_SOCIAL_INSTAGRAM \
    PUBLIC_LOCATION_NAME=$PUBLIC_LOCATION_NAME \
    PUBLIC_LOCATION_REGION=$PUBLIC_LOCATION_REGION \
    PUBLIC_LOCATION_COUNTRY=$PUBLIC_LOCATION_COUNTRY \
    PUBLIC_LOCATION_DESC=$PUBLIC_LOCATION_DESC \
    PUBLIC_SEO_KEYWORDS=$PUBLIC_SEO_KEYWORDS \
    PUBLIC_GA_ID=$PUBLIC_GA_ID \
    PUBLIC_FB_PIXEL=$PUBLIC_FB_PIXEL

RUN pnpm run build

# Stage 2: Runtime
FROM node:22-alpine AS runtime
WORKDIR /app

RUN npm install -g pnpm

COPY --from=builder /app/dist ./dist
COPY package.json pnpm-lock.yaml ./
RUN pnpm install --prod

ENV HOST=0.0.0.0
ENV PORT=4321

EXPOSE 4321
CMD ["node", "./dist/server/entry.mjs"]
